-- Batches: each batch is assigned to a trainer. Students belong to a batch.
CREATE TABLE IF NOT EXISTS skyline_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  trainer_id BIGINT NOT NULL REFERENCES skyline_trainers(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_skyline_batches_trainer_id ON skyline_batches(trainer_id);

-- Students must belong to a batch
ALTER TABLE skyline_students
  ADD COLUMN IF NOT EXISTS batch_id BIGINT REFERENCES skyline_batches(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_skyline_students_batch_id ON skyline_students(batch_id);
